echo "APT::Install-Recommends \"false\";" | sudo tee $IMGMAKER_APT_CONF_DIR/00aptitude
echo "APT::Authentication::TrustCDROM \"false\";" | sudo tee $IMGMAKER_APT_CONF_DIR/00trustcdrom
echo 'APT
{
  NeverAutoRemove
  {
	"^firmware-linux.*";
	"^linux-firmware$";
  };

  VersionedKernelPackages
  {
	# linux kernels
	"linux-image";
	"linux-headers";
	"linux-image-extra";
	"linux-signed-image";
	# kfreebsd kernels
	"kfreebsd-image";
	"kfreebsd-headers";
	# hurd kernels
	"gnumach-image";
	# (out-of-tree) modules
	".*-modules";
	".*-kernel";
	"linux-backports-modules-.*";
        # tools
        "linux-tools";
  };

  Never-MarkAuto-Sections
  {
	"metapackages";
	"restricted/metapackages";
	"universe/metapackages";
	"multiverse/metapackages";
	"oldlibs";
	"restricted/oldlibs";
	"universe/oldlibs";
	"multiverse/oldlibs";
  };
};
' | sudo tee $IMGMAKER_APT_CONF_DIR/01autoremove
echo '
// DO NOT EDIT! File autogenerated by /etc/kernel/postinst.d/apt-auto-removal
APT::NeverAutoRemove
{
   "^linux-image-4\.4\.0-1-grsec-amd64$";
   "^linux-image-4\.6\.0-1-grsec-amd64$";
   "^linux-headers-4\.4\.0-1-grsec-amd64$";
   "^linux-headers-4\.6\.0-1-grsec-amd64$";
   "^linux-image-extra-4\.4\.0-1-grsec-amd64$";
   "^linux-image-extra-4\.6\.0-1-grsec-amd64$";
   "^linux-signed-image-4\.4\.0-1-grsec-amd64$";
   "^linux-signed-image-4\.6\.0-1-grsec-amd64$";
   "^kfreebsd-image-4\.4\.0-1-grsec-amd64$";
   "^kfreebsd-image-4\.6\.0-1-grsec-amd64$";
   "^kfreebsd-headers-4\.4\.0-1-grsec-amd64$";
   "^kfreebsd-headers-4\.6\.0-1-grsec-amd64$";
   "^gnumach-image-4\.4\.0-1-grsec-amd64$";
   "^gnumach-image-4\.6\.0-1-grsec-amd64$";
   "^.*-modules-4\.4\.0-1-grsec-amd64$";
   "^.*-modules-4\.6\.0-1-grsec-amd64$";
   "^.*-kernel-4\.4\.0-1-grsec-amd64$";
   "^.*-kernel-4\.6\.0-1-grsec-amd64$";
   "^linux-backports-modules-.*-4\.4\.0-1-grsec-amd64$";
   "^linux-backports-modules-.*-4\.6\.0-1-grsec-amd64$";
   "^linux-tools-4\.4\.0-1-grsec-amd64$";
   "^linux-tools-4\.6\.0-1-grsec-amd64$";
};
' | sudo tee $IMGMAKER_APT_CONF_DIR/01autoremove-kernels

echo 'DPkg::Pre-Install-Pkgs { "/usr/bin/apt-listchanges --apt || test $? -ne 10"; };
DPkg::Tools::Options::/usr/bin/apt-listchanges::Version "2";
'| sudo tee $IMGMAKER_APT_CONF_DIR/20listchanges

echo "// Pre-configure all packages with debconf before they are installed.
// If you don't like it, comment it out.
DPkg::Pre-Install-Pkgs {\"/usr/sbin/dpkg-preconfigure --apt || true\";};
" | sudo tee $IMGMAKER_APT_CONF_DIR/70debconf
echo "[apt]
frontend=pager
email_address=root
confirm=0
save_seen=/var/lib/apt/listchanges.db
which=news
" | sudo tee $IMGMAKER_APT_DIR/listchanges.conf
